services:
  - type: web
    name: pkm-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true  # Render сам сгенерирует ключ
